### PR TITLE
terraform ecs one task awsvpc localhost config

### PR DESCRIPTION
**Pull request by pkilpo**
Hi,

First of all thanks for a great sample app!
Hope my contribution provides usefull.

I created Terraform config with following config:
- Creates own VPC
- One service
- One task of all containers
- Only public ip is ALB
- Communicates via awsvpc networking using localhost only (fast and secure)
    - This implied some small and simple changes to yelb-appserver and yelb-ui to accept some environment variables for configuring hostnames. 
- No nameserver needed
- CloudWatch logs

Check README.md in deployments\platformdeployment\AWS\tf for more info

### Test instructions for changes in yelb-appserver and yelb-ui

**yelb-appserver**

PS D:\dev\yelb\yelb\yelb-appserver> docker run --name yelb-appserver -e DB_HOST=localhost -e CACHE_HOST=localhost -it yelb-appserver ./startup.sh

and in another terminal:

PS D:\dev\yelb\yelb> docker exec -it yelb-appserver /bin/bash
root@bf8d5ecd8644:/# irb
irb(main):001:0> ENV['CACHE_HOST']
=> "localhost"
irb(main):002:0> ENV['DB_HOST']
=> "localhost"
irb(main):003:0>

**yelb-ui**

PS D:\dev\yelb\yelb\yelb-ui> docker build -t yelb-ui .

Check w/o env variable to ensure results.

With:
PS D:\dev\yelb\yelb\yelb-ui> docker run --name yelb-ui -e APPSERVER_HOST=localhost -it yelb-ui ./startup.sh

and in another terminal. 

PS D:\dev\yelb\yelb> docker exec -it yelb-ui /bin/bash

root@369409fb634c:/# cat ./proxycfg.txt
    location /api {
        proxy_pass http://localhost:4567/api;
        proxy_http_version 1.1;
    }
    gzip on;
    gzip_types text/plain text/css application/json application/javascript application/x-javascript text/xml application/xml application/xml+rss text/javascript;
    gunzip on;
root@369409fb634c:/#

without env

PS D:\dev\yelb\yelb\yelb-ui> docker run --name yelb-ui -it yelb-ui ./startup.sh                            
2022/11/02 06:38:32 [emerg] 11#11: host not found in upstream "yelb-appserver" in /etc/nginx/conf.d/default.conf:5
nginx: [emerg] host not found in upstream "yelb-appserver" in /etc/nginx/conf.d/default.conf:5
PS D:\dev\yelb\yelb\yelb-ui> 

Thats ok result if you did not have yelb-appserver container running local

### CODE REVIEW

**Comment by mreferre** [comment]
Thanks and sorry for the delay. I'd rather not change the `yelb-appserver.rb` because it's already possible to add custom DB/Redis end points if you use the `custom` RACK_ENV configuration (see [here](https://github.com/mreferre/yelb/blob/master/yelb-appserver/yelb-appserver.rb#L26-L65)). If you set `RACK_ENV=custom` you should be able to pass `YELB_DB_SERVER_ENDPOINT` and `REDIS_SERVER_ENDPOINT`. 

For the yelb-ui change to customize the app server endpoint this was long overdue but I would like to make it a separate sandboxed change that I am going to make (so that you don't have to make it in this PR). I will work on it in the next few days.

**Comment by mreferre** [comment]
I made the change for the yelb-ui: https://github.com/mreferre/yelb/commit/cd2ee67df6461caf93da9d6db2a081334d0bdf84#diff-a26524de6dd4ea5f7b30f7b0438be3311bcaa86188d576f79ba7e182c228aded

**Comment by pkilpo** [comment]
Hi that looks good I will test that custom config and then update my tf
config a bit to setup those env variables to match your changes. I try to
do that this week. 😊 BR Pekka

ma 7. marrask. 2022 klo 13.15 Massimo Re Ferrè ***@***.***>
kirjoitti:

**Comment by pkilpo** [comment]
Hi, 
I have now tested custom RACK config, it works and updated Terraform config and README accordingly.
Also checked out your latest changes so there are no additional changes to be made from my side to actual Yelb code.
It's now ready to merge in my part.

**Comment by pkilpo** [comment]
Sure, no problem.

ke 9. marrask. 2022 klo 10.44 Massimo Re Ferrè ***@***.***)
kirjoitti:

**Comment by mreferre** [comment]
I have started working on it but I realized that the TF files + instructions are vastly different than the standard format I am trying to keep throughout the repo. I would want to avoid people building / pushing images (or use latest). I would rather the IaC code to have baked in image names + tags and pull from Docker Hub (for now, in the future I may migrate to ECR Public). Something like this if you will: https://github.com/mreferre/yelb/blob/master/deployments/platformdeployment/Docker/docker-compose.yaml (this is a compose example). I would ideally like the instructions to end at the terraform `init`, `apply and `destroy` without a user having to do anything with the images. Do you think you want | have time to do this?

**Comment by pkilpo** [comment]
Yes I thought that and now it's possible when you have updated the images.
So you want to use docker repo, I can look at it. I thought too that ppl
want to make changes to start building their apps based on this. But then
they probably know what to do anyways. I guess this comes to this question
is this an app to demonstrate different cloud deployment tools or an sample
app to take as a base of building your own app. But yea I can make those
changes. ☺️

pe 11. marrask. 2022 klo 16.15 Massimo Re Ferrè ***@***.***>
kirjoitti:

**Comment by mreferre** [comment]
Yeah I want to keep this more "an app to demonstrate different cloud deployment tools". Nothing would stop anyone to use it as an app to play with etc but I would probably not take PRs for those (also becuause it could go anywhere). You can use the compose file I linked above for the specific image names + tags to use in the TF file. When/if I update the application I usually rebuild the image of the module I have changed, increased the tag number, push it to the registry and update ALL of the IaC files to point to this new tag. As an example, this is what I did when I changed the `yelb-ui` module to introduce the variable to connect to the `yelb-appserver`: https://github.com/mreferre/yelb/commit/cd2ee67df6461caf93da9d6db2a081334d0bdf84.

**Comment by pkilpo** [comment]
Hi,
That makes sense. I have now changed Terraform config to use docker images. I commented out ecr.tf contents in case you later want to use AWS ECR. Also removed push/pull part from README.
Regards, Pekka

**Comment by mreferre** [comment]
I apologize for the delay but the week before re:Invent is particularly hectic. FYI I had to make a small change to the format of the YELB_APPSERVER_ENDPOINT variable upstream and so I had to adapt your code to point to the new image I built (`0.10`) as well as the format of the variable itself in your configuration files. I tested it and it seemed to be working for me. 

Before I merge this can you have a last look at my latest changes? Thanks a ton for your support and patient.

**Comment by pkilpo** [comment]
Hi, thats totally ok, no hurry here. I checked your changes and they look ok to me. Thanks!

**Pull request merged**
