### PR TITLE
Added basic Helm chart 

### PR DESCRIPTION
**Pull request by nomisbeme**
Bump node version to 8 to allow build to work with contemporary versions of the dependencies. 
Make the app server hostname an env var (useful for kubernetes deployment, WIP)

### CODE REVIEW

**Comment by nomisbeme** [comment]
@Angelmmiguel Any idea how one might go about fixing this in an more flexible way? I can barely spell Angular...

**Comment by Angelmmiguel** [comment]
@nomisbeme yeah... the Angular CLI limitations are well known and it seems they don't plan to provide to expose internal configuration like webpack files.

What I did in the past to solve issues like this is to use a NGINX server as an entrypoint for all the application. So, based on the routes I redirect the traffic to the UI or the backend server. For example: https://github.com/Angelmmiguel/discuzzion/blob/master/dev/nginx/nginx.conf.

I think this is fine for Kubernetes (not sure about Helm), but it will need more work on the specific configuration. Also, I could be accomplished defining two services and proxying the traffic with the Ingress resource. 

I hope it helps you!

**Comment by mreferre** [comment]
looks good now

**Comment by nomisbeme** [comment]
Commenting on closed PRs is pretty silly but in case @Angelmmiguel or a Google Searcher wants to know how to solve this problem in angular without an additional routing component: https://jvandemo.com/how-to-use-environment-variables-to-configure-your-angular-application-without-a-rebuild/ Credit to @mreferre for the pointer.

**Comment by Angelmmiguel** [comment]
Thanks for the info @nomisbeme!

**Pull request merged**
